services:
  - type: web
    name: faihub
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn SocialMedia.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.9"
